### ISSUE TITLE
Support TXT records

### ISSUE THREAD

**Issue by parkan** [curl/doh#12]
This tools has been really handy for debugging DoH servers that don't support JSON requests. However, it seems that TXT records are not supported, only A AAAA NS and CNAME. This seems like it shouldn't be too hard to add, but maybe I am missing something about the decoding process.

Would it be possible to add TXT record support?

**Comment by bagder** [comment]
It not only would be possible, I really think it should support them so that this tool can be used for more DNS related checks and tests for DoH.

Are you willing to work on it?

**Comment by parkan** [comment]
my C is beyond rusty but I can give it a go, should have an evening free in the next couple of weeks

**Comment by pemensik** [comment]
Hi, I am frequent user of classic dns tools (dig, host). All of them support -t TXT parameter. However it is already used in this tool for test mode. Do you think it can be reconsidered to move test mode to different parameter letter? Maybe capital -T for example?

getdns_query, which has a bit similar output for DoT, uses second parameter as type. That is no longer available, since used for URL.

**Comment by bagder** [comment]
Sure, I think we have room to move around on things as we certainly have not carved these things in stone just yet. If `-t [TYPE]` is what we should have, then I won't have a problem to move the test mode to another flag.

**Comment by mdavids** [comment]
> Hi, I am frequent user of classic dns tools (dig, host). All of them support -t TXT parameter. However it is already used in this tool for test mode. 

I propose a '-t TXT' approach (type is TXT), similar to dig. And then also allow for other types as well. I realise this is a bit more work, but it would be really, really useful.

Still really happy with the current version though! It already saved my day.

**Comment by jalalmostafa** [comment]
I am working on this. A pull request should be ready very soon.

What do you think of `-T` option for test mode?

**Comment by jalalmostafa** [comment]
This needs closing

**Comment by bagder** [comment]
Fixed by #27
