### ISSUE TITLE
Unable to use dns.google

### ISSUE THREAD

**Issue by cmitasch** [curl/doh#19]
According to the [Google Blog](https://security.googleblog.com/2019/06/google-public-dns-over-https-doh.html) the new RFC-compliant DOH server is:
https://dns.google/dns-query

Unfurtunately the doh cli does not work with that server.
christoph@server:~$ ./doh www.google.com https://dns.google/dns.query
problem 7 decoding 787 bytes response to probe for A
problem 7 decoding 787 bytes response to probe for AAAA

It works with the deprecated URL:
https://dns.google.com/experimental

**Comment by bagder** [comment]
First, I partly blame google here for returning a `200 OK` even when you gave it a wrong URL which I understand mislead you to not detect your mistake. The official Google DoH server URL is https://dns.google/dns-query (with a dash where you had a dot).

Using this URL it works for me!

**Comment by cmitasch** [comment]
thanks, so just a typo ;)
