### ISSUE TITLE
Request for record type 'A' always returns 'AAAA'

### ISSUE THREAD

**Issue by mirfatif** [curl/doh#29]
```
~$ doh google.com
[google.com]
TTL: 215 seconds
A: 172.217.19.174
AAAA: 2a00:1450:4019:0803:0000:0000:0000:200e
~$ doh -tA google.com
[google.com]
TTL: 298 seconds
AAAA: 2a00:1450:4019:0803:0000:0000:0000:200e
~$ doh -tAAAA google.com
[google.com]
TTL: 284 seconds
AAAA: 2a00:1450:4019:0803:0000:0000:0000:200e
```
Also:

- A non-zero return  code on resolution failure would be helpful.
- Using IP address as URL enables to avoid plain DNS at all like we can do with `curl`:

        ~$ curl -s -H 'accept: application/dns-json' 'https://1.1.1.1/dns-query?name=google.com&type=A'
        {"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"google.com","type":1}],"Answer":[{"name":"google.com","type":1,"TTL":274,"data":"172.217.19.174"}]}

**Comment by jay** [comment]
Thanks. I'm not sure about the suggestions @bagder can you take a look.

**Comment by bagder** [comment]
> A non-zero return code on resolution failure would be helpful.

Indeed! Feel like writing a PR for it?

> Using IP address as URL enables to avoid plain DNS

Yes? `./doh curl.haxx.se https://1.1.1.1/dns-query` works fine... ?

**Comment by mirfatif** [comment]
@bagder 
>Indeed! Feel like writing a PR for it?

I wish I could. But all that I know is `configure && make`.

>Yes? `./doh curl.haxx.se https://1.1.1.1/dns-query` works fine... ?

Ah! my bad. I didn't test. Actually I meant `./doh curl.haxx.se 1.1.1.1[:443]`. But `/dns-query` part is not standardized, so complete URL is needed. Right?

**Comment by bagder** [comment]
You need to specify the DoH server URL in full, yes. The DoH server end point is not just "a server", it is actually a URL (template) so that a single server can offer several different variations, accessed on different paths for example.
