### ISSUE TITLE
About problem 7 

### ISSUE THREAD

**Issue by mili-tan** [curl/doh#36]
Hello, everyone 

I am trying to build a DoH Server, but I always get some error like `problem 7 decoding 80 bytes response to probe for A`
Here is a sample of my response, this is [binary](https://files.catbox.moe/esqji0.unknown)
![img](https://user-images.githubusercontent.com/24996957/107212974-b612c000-6a42-11eb-80c1-222e7c69de99.png)
I am not sure if there's something wrong with my response packet format.

Thanks very much, if someone can help me.

**Comment by jay** [comment]
IMO that's outside the scope of this project.

**Comment by mili-tan** [comment]
> IMO that's outside the scope of this project.

I am sorry
