### ISSUE TITLE
The DNS over HTTPS URL has changed

### ISSUE THREAD

**Issue by ExE-Boss** [curl/doh#4]
https://github.com/curl/doh/blob/05b11f375c80076f3998d6f40d789be5514db446/doh.c#L701

The above should now just be `https://cloudflare-dns.com/dns-query`, as per [the latest draft](https://tools.ietf.org/html/draft-ietf-doh-dns-over-https-14#section-4.1.1).

**Comment by bagder** [comment]
The draft doesn't actually specify how the URL must look, it just doesn't mention `.well-known` anymore. And Cloudflare makes both of these version work the same way... But sure, worth fixing still!

**Comment by bagder** [comment]
Thanks!
