### ISSUE TITLE
Curl DoH not working on windows 7

### ISSUE THREAD

**Issue by Hariskool** [curl/doh#9]
hey!
curl doh works fine on windows 10 after compiling and running on windows 7 or 8 it gives curl error code (6) Couldn't resolve host. if I remove the Doh its work perfectly fine on all windows os.
??

	curl = curl_easy_init();
		curl_easy_setopt(curl, CURLOPT_URL, "https://stackoverflow.com");
		curl_easy_setopt(curl, CURLOPT_DOH_URL, "https://dns.google/dns-query")
		res = curl_easy_perform(curl)
		cout << res << endl;
		curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
		curl_easy_cleanup(curl);

**Comment by bagder** [comment]
Wait, you're using the regular curl/libcurl for this right? Then this is a curl bug and not a curl-doh bug (the curl-doh is a separate tool)

**Comment by Hariskool** [comment]
okay thanks

**Comment by sergeevabc** [comment]
Where can I download a binary of `doh` for Windows 7 x64?
Being an ordinary user, I feel lost about compiling things.

**Comment by bagder** [comment]
> Where can I download a binary of doh for Windows 7 x64?

I'm not aware of anyone providing binaries of this. For any platform.
